@seed-desafio-cdc_HostAddress = https://localhost:7160

POST {{seed-desafio-cdc_HostAddress}}/api/authors
Content-Type: application/json

{
  "email": "user@example.com",
  "name": "string",
  "description": "string"
}

###

GET {{seed-desafio-cdc_HostAddress}}/api/authors

###
